[package]
name = "libsofl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[[bin]]
name = "play"
path = "bin/play/main.rs"

[[bin]]
name = "pom"
path = "bin/pom/main.rs"

[patch.crates-io]
# revm = { git = "https://github.com/bluealloy/revm/", branch = "release/v25" }
# revm-primitives = { git = "https://github.com/bluealloy/revm/", branch = "release/v25" }
revm = { path = "./revm/crates/revm" }
revm-primitives = { path = "./revm/crates/primitives" }

[dependencies]
auto_impl = "1.0"
ethers = "2.0.7"
ethers-providers = {version = "2.0.7", features = ["ws"]}
ethers-solc = {version = "2.0.7", features = ["svm-solc"]}
svm-rs = {version = "0.2.23", features = ["blocking"]}
tempfile = "3.6"
derive_more = "0.99.17"
futures = "0.3.28"
tokio = { version = "1.28.2", features = ["macros", "rt-multi-thread"] }
tracing = "0.1"
tracing-subscriber = "0.3"
config = "0.13.1"
serde = "1.0.164"
sea-orm = { version = "^0", features = ["sqlx-postgres", "sqlx-sqlite", "runtime-tokio-rustls", "macros", "mock"] }
libafl = "0.10.1"
thiserror = "1.0.40"
mockall = "0.11.2"
mockall_double = "0.3.0"
lazy_static = "1.4.0"

# misc
eyre = "0.6.8"

# lift dependencies of dependencies
reqwest = "0.11.18"
hashbrown = "0.14"
dirs = "5.0" # from svm-rs
semver = { version = "1.0", features = ["serde"] } # from svm-rs

# reth
revm = { path = "./revm/crates/revm", features = ["memory_limit", "optional_balance_check", "optional_block_gas_limit", "optional_eip3607", "optional_gas_refund", "optional_no_base_fee"] }
revm-primitives = { path = "./revm/crates/primitives", features = ["memory_limit", "optional_balance_check", "optional_block_gas_limit", "optional_eip3607", "optional_gas_refund", "optional_no_base_fee"] }
reth-config = { path = "./reth/crates/config" }
reth-primitives = { path = "./reth/crates/primitives", features = ["arbitrary"] }
reth-db = { path = "./reth/crates/storage/db", features = ["mdbx", "test-utils"] }
reth-provider = { path = "./reth/crates/storage/provider", features = ["test-utils"] }
reth-revm = { path = "./reth/crates/revm" }
reth-revm-inspectors = { path = "./reth/crates/revm/revm-inspectors" }
reth-staged-sync = { path = "./reth/crates/staged-sync" }
reth-stages = { path = "./reth/crates/stages" }
reth-interfaces = { path = "./reth/crates/interfaces", features = ["test-utils"] }
reth-transaction-pool = { path = "./reth/crates/transaction-pool" }
reth-beacon-consensus = { path = "./reth/crates/consensus/beacon" }
reth-auto-seal-consensus = { path = "./reth/crates/consensus/auto-seal" }
reth-blockchain-tree = { path = "./reth/crates/blockchain-tree" }
reth-rpc-engine-api = { path = "./reth/crates/rpc/rpc-engine-api" }
reth-rpc-builder = { path = "./reth/crates/rpc/rpc-builder" }
reth-rpc = { path = "./reth/crates/rpc/rpc" }
reth-rlp = { path = "./reth/crates/rlp" }
reth-network = { path = "./reth/crates/net/network", features = ["serde"] }
reth-network-api = { path = "./reth/crates/net/network-api" }
reth-downloaders = { path = "./reth/crates/net/downloaders", features = ["test-utils"] }
reth-tracing = { path = "./reth/crates/tracing" }
reth-tasks = { path = "./reth/crates/tasks" }
reth-net-nat = { path = "./reth/crates/net/nat" }
reth-payload-builder = { path = "./reth/crates/payload/builder" }
reth-basic-payload-builder = { path = "./reth/crates/payload/basic" }
reth-discv4 = { path = "./reth/crates/net/discv4" }
reth-metrics = { path = "./reth/crates/metrics" }
