[package]
name = "libsofl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[[bin]]
name = "migration"
path = "bin/migration/main.rs"

[[bin]]
name = "knowledge"
path = "bin/knowledge/main.rs"

[[bin]]
name = "play"
path = "bin/play/main.rs"

[[bin]]
name = "pom"
path = "bin/pom/main.rs"

[[bin]]
name = "c4c"
path = "bin/c4c/main.rs"

[features]

test-use-jsonrpc = []

[dependencies]
# programming utils
auto_impl = "1.0"
tempfile = "3.6"
derive_more = "0.99.17"
futures = "0.3.28"
rayon = "1.7.0"                                        # data parallelism
eyre = "0.6.8"                                         # error handling
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.102"
thiserror = "1.0.40"
lazy_static = "1.4.0"

# fuzzing
libafl = "0.11.1"
libafl_bolts = "0.11.1"

# user interface 
clap = { version = "4.3.19", features = ["derive"] }
toml = "0.7.6"
config = "0.13.1"

# database
sea-orm = { version = "^0", features = [
    "sqlx-postgres",
    "sqlx-sqlite",
    "runtime-tokio-rustls",
    "macros",
    "mock",
    "debug-print",
] }
sea-orm-migration = { version = "^0" }

# concurrency & async 
tokio = { version = "1.28.2", features = ["macros", "rt-multi-thread"] }
async-std = { version = "^1", features = ["attributes", "tokio1"] }

# Ethereum periphery 
ethers = "2.0.10"
ethers-providers = { version = "2.0.10", features = ["ws"] }
ethers-solc = { version = "2.0.10", features = ["svm-solc"] }
svm-rs = { version = "0.2.23", features = ["blocking"] }

# logging
tracing = "0.1"
tracing-subscriber = { version = "0.3.17", features = ["registry", "std"] }
indicatif = "0.17.5"
indicatif-log-bridge = "0.2.2"

# lift dependencies of dependencies
reqwest = "0.11.18"
hashbrown = "0.14"
dirs = "5.0"                                       # from svm-rs
semver = { version = "1.0", features = ["serde"] } # from svm-rs

# revm
revm = { git = "https://github.com/bluealloy/revm", rev = "516f62cc", features = [
    "serde",
    "memory_limit",
    "optional_balance_check",
    "optional_block_gas_limit",
    "optional_eip3607",
    "optional_gas_refund",
    "optional_no_base_fee",
] }
revm-primitives = { git = "https://github.com/bluealloy/revm", rev = "516f62cc", features = [
    "serde",
    "memory_limit",
    "optional_balance_check",
    "optional_block_gas_limit",
    "optional_eip3607",
    "optional_gas_refund",
    "optional_no_base_fee",
] }

#reth
reth = { git = "https://github.com/paradigmxyz/reth.git", tag = "v0.1.0-alpha.10" }
reth-primitives = { git = "https://github.com/paradigmxyz/reth.git", tag = "v0.1.0-alpha.10", features = [
    "arbitrary",
] }
reth-db = { git = "https://github.com/paradigmxyz/reth.git", tag = "v0.1.0-alpha.10", features = [
    "mdbx",
    "test-utils",
] }
reth-provider = { git = "https://github.com/paradigmxyz/reth.git", tag = "v0.1.0-alpha.10", features = [
    "test-utils",
] }
reth-interfaces = { git = "https://github.com/paradigmxyz/reth.git", tag = "v0.1.0-alpha.10", features = [
    "test-utils",
] }
reth-rlp = { git = "https://github.com/paradigmxyz/reth.git", tag = "v0.1.0-alpha.10" }
reth-revm = { git = "https://github.com/paradigmxyz/reth.git", tag = "v0.1.0-alpha.10" }
reth-revm-inspectors = { git = "https://github.com/paradigmxyz/reth.git", tag = "v0.1.0-alpha.10" }
reth-network-api = { git = "https://github.com/paradigmxyz/reth.git", tag = "v0.1.0-alpha.10" }
reth-beacon-consensus = { git = "https://github.com/paradigmxyz/reth.git", tag = "v0.1.0-alpha.10" }
reth-blockchain-tree = { git = "https://github.com/paradigmxyz/reth.git", tag = "v0.1.0-alpha.10" }

[dev-dependencies]
criterion = "0.4"
mockall = "0.11.2"
mockall_double = "0.3.0"

[[bench]]
name = "bench_main"
harness = false
