version: 3

tasks:
  # save a checkpoint as git commit then push to remote
  checkpoint:
    vars:
      TIMESTAMP:
        sh: date +'%Y-%m-%d %H:%M:%S UTC%z'
    cmds:
      - git add --all
      - git commit -m "checkpoint {{.TIMESTAMP}}"
      - git pull --rebase=true
      - git push

  test_jsonrpc:
    cmds:
      - cargo test tests_with_jsonrpc

  test_nodep:
    cmds:
      - cargo test tests_nodep

  test_db:
    cmds:
      - cargo test tests_with_db
