# Format the source code and commit any changes.

name: Format

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: format
  cancel-in-progress: true
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Format
      run: cargo fmt
    
    - name: Commit any changes due to lint and format
      uses: EndBug/add-and-commit@v7.2.1
      with:
        add: .
        author_name: GitHub Action
        message: Changes by format action
