# Format the source code and commit any changes.

name: Format

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: format
  cancel-in-progress: true
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.BOT_ACCESS_TOKEN }}
        ref: main
    
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

    - name: Format
      run: cargo fmt
    
    - name: Commit changes
      uses: EndBug/add-and-commit@v9.1.3
      with:
        author_name: GitHub Action
        author_email: bot@troublor.xyz
        message: 'Changes by format script [skip ci]'
        add: .
        github_token: ${{ secrets.BOT_ACCESS_TOKEN }}
