name: Cargo test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  
concurrency:
  group: test
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: main
        submodules: recursive
        
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Build
      run: cargo build --verbose
      
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env: 
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      
    - name: Run tests without external dependency
      run: cargo test tests_nodep
      
    - name: Run tests with jsonrpc dependency
      run: |
        export SOFL__JSONRPC__ENDPOINT=https://libsofl.eth.troublor.xyz/v1/mainnet
        export SOFL__JSONRPC__CLOUDFLARE_CLIENT_ID=${{ secrets.CLOUDFLARE_CLIENT_ID }}
        export SOFL__JSONRPC__CLOUDFLARE_CLIENT_SECRET=${{ secrets.CLOUDFLARE_CLIENT_SECRET }}
        cargo test tests_with_jsonrpc
