name: Cargo test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: main
        submodules: recursive
        
    - name: Build
      run: cargo build --verbose
      
    - name: Run tests without external dependency
      run: cargo test tests_nodep
      
    - name: Run tests with jsonrpc dependency
      run: |
        export SOFL__JSONRPC__ENDPOINT=https://libsofl.eth.troublor.xyz/v1/mainnet
        export SOFL__JSONRPC__CLOUDFLARE_CLIENT_ID=${{ secrets.CLOUDFLARE_CLIENT_ID }}
        export SOFL__JSONRPC__CLOUDFLARE_CLIENT_SECRET=${{ secrets.CLOUDFLARE_CLIENT_SECRET }}
        cargo test tests_with_jsonrpc
